import { isSingleLineBalanced } from "../analyzer/isSingleLineBalanced";
import { fixDoneCallbacks } from "../transformers/fixDoneCallbacks";
import { fixRealTimingHelpers } from "../transformers/fixRealTimingHelpers";
import { fixSetTimeoutDelays } from "../transformers/fixSetTimeoutDelay";
import { fixSharedState } from "../transformers/fixSharedState";
import { validateOutput } from "../validators/validateOutput";

type FlakyType = "async wait" | "network";
type AsyncSubType =
  | "setTimeout"
  | "done callback"
  | "real timing"
  | "shared state"
  | "waitFor wrap";
export type Framework = "jest" | "vitest";

interface RuleEngineInput {
  testCode: string;
  flakyType: FlakyType;
  framework: Framework;
  testName: string;
}

interface RuleEngineOutput {
  fixedCode: string;
  explanation: string;
}

export const getProperWaitReplacement = (framework: Framework): string => {
  switch (framework) {
    case "jest":
    case "vitest":
      return "await waitFor(() => {})";
  }
};

const addWaitForImport = (
  code: string,
  framework: "jest" | "vitest",
): string => {
  const testingLibraryImportPattern =
    /import\s*\{([^}]+)\}\s*from\s*['"]@testing-library\/[^'"]+['"]/;

  if (testingLibraryImportPattern.test(code)) {
    return code.replace(testingLibraryImportPattern, (match, imports) => {
      if (imports.includes("waitFor")) return match;
      return match.replace(imports, `${imports.trim()}, waitFor`);
    });
  }
  return `import { waitFor } from '@testing-library/dom';\n` + code;
};

const injectBeforeFirstTest = (
  code: string,
  injection: string,
  changes: string[],
  changeMessage: string,
): string => {
  const firstTestPattern = /^([ \t]*(?:it|test)\s*\()/m;

  if (firstTestPattern.test(code)) {
    changes.push(changeMessage);
    return code.replace(firstTestPattern, `${injection}\n\n$1`);
  }

  changes.push(changeMessage);
  return injection + "\n\n" + code;
};

export const injectAfterLastTest = (
  code: string,
  injection: string,
  changes: string[],
  changeMessage: string,
): string => {
  const lastIndex = code.lastIndexOf("});");

  if (lastIndex !== -1) {
    changes.push(changeMessage);
    return code.slice(0, lastIndex) + injection + "\n" + code.slice(lastIndex);
  }

  return code + "\n" + injection;
};

const buildFetchMock = (mockPrefix: string): string =>
  `beforeEach(() => {\n` +
  `  ${mockPrefix}.spyOn(global, 'fetch').mockResolvedValue({\n` +
  `    ok: true,\n` +
  `    status: 200,\n` +
  `    json: async () => ({}),\n` +
  `  } as Response);\n` +
  `});`;

const buildAxiosMock = (mockPrefix: string): string =>
  `${mockPrefix}.mock('axios');\n` +
  `beforeEach(() => {\n` +
  `  const axios = require('axios');\n` +
  `  axios.get.mockResolvedValue({ data: {}, status: 200 });\n` +
  `  axios.post.mockResolvedValue({ data: {}, status: 200 });\n` +
  `});`;

const buildNockMock = (): string =>
  `const nock = require('nock');\n` +
  `beforeEach(() => {\n` +
  `  nock.cleanAll();\n` +
  `  nock(process.env.API_URL || 'http://localhost')\n` +
  `    .get(/.*/).reply(200, {})\n` +
  `    .post(/.*/).reply(200, {});\n` +
  `});`;

const buildExplanation = (
  testName: string,
  flakyType: FlakyType,
  changes: string[],
): string => {
  if (changes.length === 0) {
    return `No automated fix could be applied to "${testName}". Manual review recommended.`;
  }

  const changeList = changes.map((c) => `- ${c}`).join("\n");

  return (
    `## Automated Fix: ${flakyType === "async wait" ? "Async/Await Issue" : "Network Dependency"}\n\n` +
    `**Test:** \`${testName}\`\n\n` +
    `**Issue:** This test was detected as flaky due to ${flakyType} problems.\n\n` +
    `**Changes applied:**\n${changeList}\n\n` +
    `> This fix was automatically generated by FlakeyRadar. Please review before merging.`
  );
};

const fixNetworkJestVitest = (
  code: string,
  framework: "jest" | "vitest",
  changes: string[],
): string => {
  let fixedCode = code;
  const mockPrefix = framework === "vitest" ? "vi" : "jest";

  const hasRealFetch = /\bfetch\s*\(\s*['"`]https?:\/\//g.test(fixedCode);
  const hasRealAxios =
    /\baxios\.(get|post|put|delete|patch)\s*\(\s*['"`]https?:\/\//g.test(
      fixedCode,
    );

  const alreadyMocked =
    fixedCode.includes("jest.mock") ||
    fixedCode.includes("vi.mock") ||
    fixedCode.includes("jest.spyOn") ||
    fixedCode.includes("vi.spyOn") ||
    fixedCode.includes("msw") ||
    fixedCode.includes("nock");

  if ((hasRealFetch || hasRealAxios) && !alreadyMocked) {
    if (hasRealFetch) {
      fixedCode = injectBeforeFirstTest(
        fixedCode,
        buildFetchMock(mockPrefix),
        changes,
        "Added fetch mock to prevent real network calls",
      );
    }

    if (hasRealAxios) {
      fixedCode = injectBeforeFirstTest(
        fixedCode,
        buildAxiosMock(mockPrefix),
        changes,
        "Added axios mock to prevent real network calls",
      );
    }
  }

  if (
    changes.length > 0 &&
    !fixedCode.includes("afterEach") &&
    !fixedCode.includes("afterAll")
  ) {
    fixedCode = injectAfterLastTest(
      fixedCode,
      `\nafterEach(() => {\n  ${mockPrefix}.restoreAllMocks();\n});`,
      changes,
      "Added afterEach cleanup to restore mocks between tests",
    );
  }

  return fixedCode;
};

const fixWaitForWrapping = (
  code: string,
  framework: Framework,
  changes: string[],
): string => {
  if (framework !== "jest" && framework !== "vitest") {
    return code;
  }

  if (code.includes("waitFor")) return code;

  const hasAsyncActivity = code.includes("await") || code.includes(".then(");

  if (!hasAsyncActivity) return code;

  let fixedCode = code;

  fixedCode = fixedCode.replace(
    /([ \t]*)(expect\([^)]+\)\.[a-zA-Z]+\([^)]*\));?/g,
    (match, indent, expectStatement) => {
      if (!isSingleLineBalanced(match)) return match;

      if (fixedCode.includes(`waitFor(() => {\n${indent}${expectStatement}`)) {
        return match;
      }

      changes.push("Wrapped assertion in waitFor to handle async DOM updates");
      return (
        `${indent}await waitFor(() => {\n` +
        `${indent}  ${expectStatement};\n` +
        `${indent}});`
      );
    },
  );

  return fixedCode;
};

const fixAsyncWait = (input: RuleEngineInput): RuleEngineOutput => {
  const { testCode, framework, testName } = input;
  let fixedCode = testCode;
  const changes: string[] = [];

  fixedCode = fixSetTimeoutDelays(fixedCode, framework, changes);

  fixedCode = fixDoneCallbacks(fixedCode, changes);

  fixedCode = fixRealTimingHelpers(fixedCode, framework, changes);

  fixedCode = fixSharedState(fixedCode, changes);

  fixedCode = fixWaitForWrapping(fixedCode, framework, changes);

  if (
    changes.some((c) => c.includes("waitFor")) &&
    (framework === "jest" || framework === "vitest") &&
    !fixedCode.includes("waitFor")
  ) {
    fixedCode = addWaitForImport(fixedCode, framework);
  }

  console.log(buildExplanation(testName, "async wait", changes));

  return {
    fixedCode,
    explanation: buildExplanation(testName, "async wait", changes),
  };
};

const fixNetwork = (input: RuleEngineInput): RuleEngineOutput => {
  const { testCode, framework, testName } = input;
  let fixedCode = testCode;
  const changes: string[] = [];

  if (framework === "jest" || framework === "vitest") {
    fixedCode = fixNetworkJestVitest(fixedCode, framework, changes);
  }
  return {
    fixedCode,
    explanation: buildExplanation(testName, "network", changes),
  };
};

export const RuleEngineService = {
  applyFix(input: RuleEngineInput): RuleEngineOutput {
    const { flakyType, testCode, testName } = input;

    let result: RuleEngineOutput;

    if (flakyType === "async wait") {
      result = fixAsyncWait(input);
    } else if (flakyType === "network") {
      result = fixNetwork(input);
    } else { 

    return {
      fixedCode: input.testCode,
      explanation: `No fix rule matched for flaky type "${flakyType}". Manual review recommended.`,
    };

  }

    const { safe, reason } = validateOutput(
      testCode,
      result.fixedCode,
      testName,
    );

    if (!safe) {
      return {
        fixedCode: testCode,
        explanation:
          `## Fix Aborted — Content Loss Detected\n\n` +
          `**Test:** \`${testName}\`\n\n` +
          `**Reason:** ${reason}\n\n` +
          `**Action:** Original code preserved. Manual review is required.\n\n` +
          `> This safety check was triggered by FlakeyRadar's content loss guard.`,
      };
    }

    return result;
  },
};
