type FlakyType = "async wait" | "network";
type AsyncSubType =
  | "setTimeout"
  | "done callback"
  | "real timing"
  | "shared state"
  | "waitFor wrap";
type Framework = "jest" | "vitest" | "mocha" | "cypress" | "playwright";

interface RuleEngineInput {
  testCode: string;
  flakyType: FlakyType;
  framework: Framework;
  testName: string;
}

interface RuleEngineOutput {
  fixedCode: string;
  explanation: string;
}

const getProperWaitReplacement = (framework: Framework): string => {
  switch (framework) {
    case "jest":
    case "vitest":
      return "await waitFor(() => {})";
    case "mocha":
      return "await new Promise(resolve => setImmediate(resolve))";
    case "playwright":
      return "await page.waitForLoadState('networkidle')";
    case "cypress":
      return "/* cy commands are already queued — remove this delay */";
  }
};

const addWaitForImport = (
  code: string,
  framework: "jest" | "vitest",
): string => {
  const testingLibraryImportPattern =
    /import\s*\{([^}]+)\}\s*from\s*['"]@testing-library\/[^'"]+['"]/;

  if (testingLibraryImportPattern.test(code)) {
    return code.replace(testingLibraryImportPattern, (match, imports) => {
      if (imports.includes("waitFor")) return match;
      return match.replace(imports, `${imports.trim()}, waitFor`);
    });
  }
  return `import { waitFor } from '@testing-library/dom';\n` + code;
};

const injectBeforeFirstTest = (
  code: string,
  injection: string,
  changes: string[],
  changeMessage: string,
): string => {
  const firstTestPattern = /^([ \t]*(?:it|test)\s*\()/m;

  if (firstTestPattern.test(code)) {
    changes.push(changeMessage);
    return code.replace(firstTestPattern, `${injection}\n\n$1`);
  }

  changes.push(changeMessage);
  return injection + "\n\n" + code;
};

const injectAfterLastTest = (
  code: string,
  injection: string,
  changes: string[],
  changeMessage: string,
): string => {
  const lastIndex = code.lastIndexOf("});");

  if (lastIndex !== -1) {
    changes.push(changeMessage);
    return code.slice(0, lastIndex) + injection + "\n" + code.slice(lastIndex);
  }

  return code + "\n" + injection;
};

const buildFetchMock = (mockPrefix: string): string =>
  `beforeEach(() => {\n` +
  `  ${mockPrefix}.spyOn(global, 'fetch').mockResolvedValue({\n` +
  `    ok: true,\n` +
  `    status: 200,\n` +
  `    json: async () => ({}),\n` +
  `  } as Response);\n` +
  `});`;

const buildAxiosMock = (mockPrefix: string): string =>
  `${mockPrefix}.mock('axios');\n` +
  `beforeEach(() => {\n` +
  `  const axios = require('axios');\n` +
  `  axios.get.mockResolvedValue({ data: {}, status: 200 });\n` +
  `  axios.post.mockResolvedValue({ data: {}, status: 200 });\n` +
  `});`;

const buildNockMock = (): string =>
  `const nock = require('nock');\n` +
  `beforeEach(() => {\n` +
  `  nock.cleanAll();\n` +
  `  nock(process.env.API_URL || 'http://localhost')\n` +
  `    .get(/.*/).reply(200, {})\n` +
  `    .post(/.*/).reply(200, {});\n` +
  `});`;

const buildExplanation = (
  testName: string,
  flakyType: FlakyType,
  changes: string[],
): string => {
  if (changes.length === 0) {
    return `No automated fix could be applied to "${testName}". Manual review recommended.`;
  }

  const changeList = changes.map((c) => `- ${c}`).join("\n");

  return (
    `## Automated Fix: ${flakyType === "async wait" ? "Async/Await Issue" : "Network Dependency"}\n\n` +
    `**Test:** \`${testName}\`\n\n` +
    `**Issue:** This test was detected as flaky due to ${flakyType} problems.\n\n` +
    `**Changes applied:**\n${changeList}\n\n` +
    `> This fix was automatically generated by FlakeyRadar. Please review before merging.`
  );
};

const fixNetworkJestVitest = (
  code: string,
  framework: "jest" | "vitest",
  changes: string[],
): string => {
  let fixedCode = code;
  const mockPrefix = framework === "vitest" ? "vi" : "jest";

  const hasRealFetch = /\bfetch\s*\(\s*['"`]https?:\/\//g.test(fixedCode);
  const hasRealAxios =
    /\baxios\.(get|post|put|delete|patch)\s*\(\s*['"`]https?:\/\//g.test(
      fixedCode,
    );

  const alreadyMocked =
    fixedCode.includes("jest.mock") ||
    fixedCode.includes("vi.mock") ||
    fixedCode.includes("jest.spyOn") ||
    fixedCode.includes("vi.spyOn") ||
    fixedCode.includes("msw") ||
    fixedCode.includes("nock");

  if ((hasRealFetch || hasRealAxios) && !alreadyMocked) {
    if (hasRealFetch) {
      fixedCode = injectBeforeFirstTest(
        fixedCode,
        buildFetchMock(mockPrefix),
        changes,
        "Added fetch mock to prevent real network calls",
      );
    }

    if (hasRealAxios) {
      fixedCode = injectBeforeFirstTest(
        fixedCode,
        buildAxiosMock(mockPrefix),
        changes,
        "Added axios mock to prevent real network calls",
      );
    }
  }

  if (
    changes.length > 0 &&
    !fixedCode.includes("afterEach") &&
    !fixedCode.includes("afterAll")
  ) {
    fixedCode = injectAfterLastTest(
      fixedCode,
      `\nafterEach(() => {\n  ${mockPrefix}.restoreAllMocks();\n});`,
      changes,
      "Added afterEach cleanup to restore mocks between tests",
    );
  }

  return fixedCode;
};

const fixNetworkMocha = (code: string, changes: string[]): string => {
  let fixedCode = code;

  const hasRealFetch = /\bfetch\s*\(\s*['"`]https?:\/\//g.test(fixedCode);
  const hasRealAxios =
    /\baxios\.(get|post|put|delete|patch)\s*\(\s*['"`]https?:\/\//g.test(
      fixedCode,
    );
  const alreadyMocked =
    fixedCode.includes("nock") || fixedCode.includes("sinon");

  if ((hasRealFetch || hasRealAxios) && !alreadyMocked) {
    fixedCode = injectBeforeFirstTest(
      fixedCode,
      buildNockMock(),
      changes,
      "Added nock interceptor to prevent real network calls",
    );
  }

  return fixedCode;
};

const fixNetworkCypress = (code: string, changes: string[]): string => {
  let fixedCode = code;

  const alreadyIntercepted = fixedCode.includes("cy.intercept");
  const hasNavigation =
    fixedCode.includes("cy.visit") || fixedCode.includes("cy.request");

  if (hasNavigation && !alreadyIntercepted) {
    fixedCode = fixedCode.replace(
      /([ \t]*)(cy\.visit\s*\([^)]+\))/,
      (match, indent, visitCall) => {
        changes.push(
          "Added cy.intercept to stub network requests before cy.visit",
        );
        return (
          `${indent}cy.intercept('GET', '**/api/**', { statusCode: 200, body: {} }).as('apiCall');\n` +
          `${indent}${visitCall}`
        );
      },
    );
  }

  return fixedCode;
};

const fixNetworkPlaywright = (code: string, changes: string[]): string => {
  let fixedCode = code;

  const alreadyRouted = fixedCode.includes("page.route");
  const hasNavigation =
    fixedCode.includes("page.goto") || fixedCode.includes("page.navigate");

  if (hasNavigation && !alreadyRouted) {
    fixedCode = fixedCode.replace(
      /([ \t]*)(await\s+page\.goto\s*\([^)]+\))/,
      (match, indent, gotoCall) => {
        changes.push(
          "Added page.route to intercept network requests before navigation",
        );
        return (
          `${indent}await page.route('**/api/**', route => route.fulfill({ status: 200, body: '{}' }));\n` +
          `${indent}${gotoCall}`
        );
      },
    );
  }

  return fixedCode;
};

const fixAsyncWait = (input: RuleEngineInput): RuleEngineOutput => {
  const { testCode, framework, testName } = input;
  let fixedCode = testCode;
  const changes: string[] = [];

  const setTimeoutDelayPattern =
    /await\s+new\s+Promise\(\s*(\w+)\s*=>\s*setTimeout\s*\(\s*\1\s*,\s*[^)]+\)\s*\)/g;

  fixedCode = fixedCode.replace(setTimeoutDelayPattern, () => {
    changes.push("Replaced arbitrary setTimeout delay with proper async wait");
    return getProperWaitReplacement(framework);
  });

  const doneCallbackPattern = /\(\s*done\s*\)\s*=>\s*\{/g;
  const beforeDone = fixedCode;

  fixedCode = fixedCode.replace(doneCallbackPattern, () => {
    changes.push("Converted done-callback pattern to async/await");
    return "async () => {";
  });

  if (fixedCode !== beforeDone) {
    fixedCode = fixedCode.replace(/\bdone\(\s*\)\s*;?/g, "");
  }

  if (
    (framework === "jest" || framework === "vitest" || framework === "mocha") &&
    !fixedCode.includes("waitFor")
  ) {
    const hasAsyncActivity =
      fixedCode.includes("await") || fixedCode.includes(".then(");

    if (hasAsyncActivity) {
      fixedCode = fixedCode.replace(
        /([ \t]*)(expect\([^)]+\)\.[a-zA-Z]+\([^)]*\));?/g,
        (match, indent, expectStatement) => {
          if (
            fixedCode.includes(`waitFor(() => {\n${indent}${expectStatement}`)
          ) {
            return match;
          }
          changes.push(
            "Wrapped assertion in waitFor to handle async DOM updates",
          );
          return `${indent}await waitFor(() => {\n${indent}  ${expectStatement};\n${indent}});`;
        },
      );
    }
  }

  if (framework === "playwright") {
    fixedCode = fixedCode.replace(
      /await\s+page\.waitForTimeout\s*\(\s*\d+\s*\)/g,
      () => {
        changes.push("Replaced page.waitForTimeout with page.waitForLoadState");
        return "await page.waitForLoadState('networkidle')";
      },
    );
  }

  if (framework === "cypress") {
    fixedCode = fixedCode.replace(/cy\.wait\s*\(\s*\d+\s*\)/g, () => {
      changes.push(
        "Replaced cy.wait(number) — update the TODO with your actual assertion",
      );
      return `/* TODO: replace with cy.get('[data-testid="..."]').should('be.visible') */`;
    });
  }

  if (
    changes.some((c) => c.includes("waitFor")) &&
    (framework === "jest" || framework === "vitest") &&
    !fixedCode.includes("waitFor")
  ) {
    fixedCode = addWaitForImport(fixedCode, framework);
  }

  console.log(buildExplanation(testName, "async wait", changes));

  return {
    fixedCode,
    explanation: buildExplanation(testName, "async wait", changes),
  };
};

const fixNetwork = (input: RuleEngineInput): RuleEngineOutput => {
  const { testCode, framework, testName } = input;
  let fixedCode = testCode;
  const changes: string[] = [];

  if (framework === "jest" || framework === "vitest") {
    fixedCode = fixNetworkJestVitest(fixedCode, framework, changes);
  } else if (framework === "mocha") {
    fixedCode = fixNetworkMocha(fixedCode, changes);
  } else if (framework === "cypress") {
    fixedCode = fixNetworkCypress(fixedCode, changes);
  } else if (framework === "playwright") {
    fixedCode = fixNetworkPlaywright(fixedCode, changes);
  }

  return {
    fixedCode,
    explanation: buildExplanation(testName, "network", changes),
  };
};

export const RuleEngineService = {
  applyFix(input: RuleEngineInput): RuleEngineOutput {
    const { flakyType } = input;

    if (flakyType === "async wait") return fixAsyncWait(input);
    if (flakyType === "network") return fixNetwork(input);

    return {
      fixedCode: input.testCode,
      explanation: `No fix rule matched for flaky type "${flakyType}". Manual review recommended.`,
    };
  },
};
